#image:
#  - Visual Studio 2017
#clone_folder: c:\projects\source\Testing\This\File\Is\Even\Being\Read
version: 1.0.{build}
image: Visual Studio 2017

configuration:
- Debug
- Release

before_build:
  - cmd: >-
      cd Game
  
      git submodule update --init --recursive

      mkdir build
      
      cd build
      
      cmake -G "Visual Studio 15 2017 Win64" ../
    
build:
  project: Game/build/HonoursProject.vcxproj
  parallel: true
  verbosity: minimal
  
after_build:
  - cmd: >-
      mkdir play

      echo D | xcopy %APPVEYOR_BUILD_FOLDER%\Game\build\%CONFIGURATION%\*.* %APPVEYOR_BUILD_FOLDER%\Game\build\play /y

      echo D | xcopy %APPVEYOR_BUILD_FOLDER%\Game\build\%CONFIGURATION%\* %APPVEYOR_BUILD_FOLDER%\Game\build\play /s /y

      7z a HonoursProject_%CONFIGURATION%.zip %APPVEYOR_BUILD_FOLDER%/Game/build/GameRecords %APPVEYOR_BUILD_FOLDER%/Game/build/play
      

artifacts:
  path: Game/build/HonoursProject_%CONFIGURATION%.zip
  name: HonoursProject_%CONFIGURATION%